### ISSUE TITLE
Button text is cropped on Windows

### ISSUE THREAD

**Issue by alisonlange45** [mac-comp127/kilt-graphics#21]
This code:

    public static void main(String[] args) {
        canvasTest = canvas = new CanvasWindow("Test", CANVAS_WIDTH, CANVAS_HEIGHT);
        Button basicTest = new Button("Button test");
        basicTest.setPosition(CANVAS_WIDTH/2, CANVAS_HEIGHT / 2);
        canvas.add(basicTest);
    }

…produces this result:

![Screenshot (345)](https://user-images.githubusercontent.com/70910705/96819664-b9c5fc80-13e9-11eb-9978-daf2b844686d.png)

Button is properly sized for its text on Mac.

**Comment by pcantrell** [comment]
Fixed in #23
