### ISSUE TITLE
Add Rotation Method 

### ISSUE THREAD

**Issue by hayleyhadges** [mac-comp127/kilt-graphics#3]
For our project, we would like to use mouse motion to rotate a triangle-shaped path (from 127 graphics). We would like to be able to give this method a desired angle, in which the path object rotates said angle. The triangle should stay centered in the same spot, just rotating.

It could also be useful to use the rotate method on all images!

**Comment by pcantrell** [comment]
The ability to rotate arbitrary GraphicsObjects is a clear omission, and something we should add. Unfortunately, it will take a bit of work, so it won’t arrive quickly — but this is definitely something we’ll add.
